spring:
  application:
    name: notification-service
  activemq:
    broker-url: ${ACTIVEMQ_URL:tcp://localhost:61616}
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASS:admin}
  jms:
    listener:
      acknowledge-mode: auto

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
  level:
    com.stripe.payment: DEBUG
